import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AGA Super Agent',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        

        <div className="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <Link  href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">AGA Super Agent</span>
          </Link >
          <div className="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
              <Link href="/about" type="button" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">About Hackathon</Link>
          </div>
          <div className="items-center hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
          </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
